version: '3'

services:
  app:
    build: 
      context: py/server/
      dockerfile : Dockerfile
    container_name: kilo-service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kilo-network

  db:
    image: postgres:15
    container_name: kilo-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kilo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5       

volumes:
  pgdata:

networks:
  kilo-network: 