version: "3"

services:
  postgres:
    env_file: .env
    networks:
      - enchantments_network
    image: postgres:13.2
    environment:
      POSTGRES_USER: "${postgresUser}"
      POSTGRES_PASSWORD: "${postgresPassword}"
      POSTGRES_DB: "${postgresDb}"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U enchantments"]
      interval: 2s
      timeout: 2s
      retries: 15

  enchantments-server:
    env_file: .env
    networks:
      - enchantments_network
    build:
      context: ./server
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  static_volume: {}
networks:
  enchantments_network: {}
